name: Compile SCSS and Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Sass
        run: npm install -g sass

      - name: Compile SCSS to CSS
        run: sass styles/style.scss styles/style.css

      - name: Commit compiled CSS
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add styles/style.css
          git commit -m "Auto-compile SCSS" || echo "No changes to commit"
          git push
